<?php
// profile_report.php
declare(strict_types=1);

// dev-friendly error display (remove or disable on production)
ini_set('display_errors', '1');
ini_set('display_startup_errors', '1');
error_reporting(E_ALL);

// Require DB config and FPDF
require __DIR__ . '/config.php';   
require __DIR__ . '/fpdf.php';     

// Very small helper to sanitize output for PDF text
function pdf_safe(string $s): string {
    return trim(html_entity_decode(strip_tags((string)$s)));
}

// Read id from GET
$id = isset($_GET['id']) ? (int) $_GET['id'] : 0;
if ($id <= 0) {
    http_response_code(400);
    echo "Missing or invalid id parameter. Use ?id=1";
    exit;
}

try {
    $stmt = $pdo->prepare("SELECT * FROM students WHERE id = :id LIMIT 1");
    $stmt->execute([':id' => $id]);
    $student = $stmt->fetch();

    if (!$student) {
        http_response_code(404);
        echo "Student not found.";
        exit;
    }

    // Map status numeric to label
    $statusMap = [
        1 => 'Active',
        0 => 'Pending',
        2 => 'Inactive'
    ];
    $statusLabel = $statusMap[(int)($student['status'] ?? 1)] ?? 'Unknown';

    // Build PDF
    $pdf = new FPDF('P', 'mm', 'A4');
    $pdf->SetAutoPageBreak(true, 20);
    $pdf->AddPage();

    // Header
    $pdf->SetFont('Arial', 'B', 16);
    $pdf->Cell(0, 8, 'Profile Summary', 0, 1, 'C');
    $pdf->Ln(4);

    $pdf->SetFont('Arial', '', 11);
    $pdf->Cell(40, 7, 'Generated:', 0, 0);
    $pdf->Cell(0, 7, date('Y-m-d H:i:s'), 0, 1);
    $pdf->Ln(4);

    $pdf->SetDrawColor(200,200,200);
    $pdf->SetLineWidth(0.3);
    $pdf->Line(10, $pdf->GetY(), 200, $pdf->GetY());
    $pdf->Ln(6);

    // Student fields (two-column like layout)
    $pdf->SetFont('Arial', 'B', 11);
    $pdf->Cell(50, 7, 'Full name:');
    $pdf->SetFont('Arial', '', 11);
    $pdf->Cell(0, 7, pdf_safe($student['full_name'] ?? ''), 0, 1);

    $pdf->SetFont('Arial', 'B', 11);
    $pdf->Cell(50, 7, 'Student ID:');
    $pdf->SetFont('Arial', '', 11);
    $pdf->Cell(0, 7, pdf_safe($student['student_id'] ?? ''), 0, 1);

    $pdf->SetFont('Arial', 'B', 11);
    $pdf->Cell(50, 7, 'Email:');
    $pdf->SetFont('Arial', '', 11);
    $pdf->Cell(0, 7, pdf_safe($student['email'] ?? ''), 0, 1);

    $pdf->SetFont('Arial', 'B', 11);
    $pdf->Cell(50, 7, 'Date of birth:');
    $pdf->SetFont('Arial', '', 11);
    $pdf->Cell(0, 7, pdf_safe($student['dob'] ?? ''), 0, 1);

    $pdf->SetFont('Arial', 'B', 11);
    $pdf->Cell(50, 7, 'Course:');
    $pdf->SetFont('Arial', '', 11);
    $pdf->Cell(0, 7, pdf_safe($student['course'] ?? ''), 0, 1);

    $pdf->SetFont('Arial', 'B', 11);
    $pdf->Cell(50, 7, 'Enrollment date:');
    $pdf->SetFont('Arial', '', 11);
    $pdf->Cell(0, 7, pdf_safe($student['enrollment_date'] ?? ''), 0, 1);

    $pdf->SetFont('Arial', 'B', 11);
    $pdf->Cell(50, 7, 'Status:');
    $pdf->SetFont('Arial', '', 11);
    $pdf->Cell(0, 7, $statusLabel, 0, 1);

    // Optional: created_at
    if (!empty($student['created_at'])) {
        $pdf->SetFont('Arial', 'B', 11);
        $pdf->Cell(50, 7, 'Registered at:');
        $pdf->SetFont('Arial', '', 11);
        $pdf->Cell(0, 7, pdf_safe($student['created_at']), 0, 1);
    }

    $pdf->Ln(8);
    $pdf->SetFont('Arial', 'I', 9);
    $pdf->Cell(0, 6, 'Generated by Student Management System', 0, 1, 'C');

    // Output as download
    $filename = 'profile_' . preg_replace('/[^A-Za-z0-9_\-]/', '_', ($student['student_id'] ?? 'unknown')) . '.pdf';
    header('Content-Type: application/pdf');
    header('Content-Disposition: attachment; filename="' . $filename . '"');
    header('Cache-Control: private, max-age=0, must-revalidate');
    $pdf->Output('D', $filename);
    exit;

} catch (Exception $e) {
    http_response_code(500);
    echo "Server error: " . htmlspecialchars($e->getMessage());
    exit;
}
